// <auto-generated />
using System;
using CandidateSelectionService.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CandidateSelectionService.DAL.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250911211553_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_user_id");

                    b.Property<int>("DataId")
                        .HasColumnType("integer")
                        .HasColumnName("data_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("WorkScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("work_schedule_id");

                    b.HasKey("Id")
                        .HasName("candidate_pkey");

                    b.HasIndex("DataId")
                        .IsUnique();

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("candidate", "hr");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.DataCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateOnly>("DateBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middlename");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("data_candidate_pkey");

                    b.ToTable("data_candidate", "hr");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataId")
                        .HasColumnType("integer")
                        .HasColumnName("data_id");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("employment_date");

                    b.Property<int>("WorkScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("work_schedule_id");

                    b.HasKey("Id")
                        .HasName("employee_pkey");

                    b.HasIndex("DataId")
                        .IsUnique();

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("employee", "hr");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_token_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", "auth");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.SocialNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataCandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("data_candidate_id");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("social_network_pkey");

                    b.HasIndex("DataCandidateId");

                    b.HasIndex("TypeId");

                    b.ToTable("social_network", "hr");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.SocialNetworkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("social_network_type_pkey");

                    b.ToTable("social_network_type", "hr");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middlename");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.ToTable("user", "auth");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.Verification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("SearchData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_data");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("verification_pkey");

                    b.ToTable("verification", "verification");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.VerificationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("VerificationId")
                        .HasColumnType("integer")
                        .HasColumnName("verification_id");

                    b.HasKey("Id")
                        .HasName("verification_event_pkey");

                    b.HasIndex("VerificationId");

                    b.ToTable("verification_event", "verification");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.VerificationEventResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateOnly>("DateBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middlename");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("VerificationEventId")
                        .HasColumnType("integer")
                        .HasColumnName("verification_event_id");

                    b.Property<string>("WorkSchedule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_schedule");

                    b.HasKey("Id")
                        .HasName("verification_event_result_pkey");

                    b.HasIndex("VerificationEventId");

                    b.ToTable("verification_event_result", "verification");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("work_schedule_pkey");

                    b.ToTable("work_schedule", "hr");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.Candidate", b =>
                {
                    b.HasOne("CandidateSelectionService.Core.Entities.DataCandidate", "DataCandidate")
                        .WithOne("Candidate")
                        .HasForeignKey("CandidateSelectionService.Core.Entities.Candidate", "DataId")
                        .IsRequired();

                    b.HasOne("CandidateSelectionService.Core.Entities.WorkSchedule", "WorkSchedule")
                        .WithMany("Candidates")
                        .HasForeignKey("WorkScheduleId")
                        .IsRequired()
                        .HasConstraintName("candidate_work_schedule_id_fkey");

                    b.Navigation("DataCandidate");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.Employee", b =>
                {
                    b.HasOne("CandidateSelectionService.Core.Entities.DataCandidate", "DataCandidate")
                        .WithOne("Employee")
                        .HasForeignKey("CandidateSelectionService.Core.Entities.Employee", "DataId")
                        .IsRequired();

                    b.HasOne("CandidateSelectionService.Core.Entities.WorkSchedule", "WorkSchedule")
                        .WithMany("Employees")
                        .HasForeignKey("WorkScheduleId")
                        .IsRequired()
                        .HasConstraintName("employee_work_schedule_id_fkey");

                    b.Navigation("DataCandidate");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("CandidateSelectionService.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("refresh_token_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.SocialNetwork", b =>
                {
                    b.HasOne("CandidateSelectionService.Core.Entities.DataCandidate", "DataCandidate")
                        .WithMany("SocialNetworks")
                        .HasForeignKey("DataCandidateId")
                        .IsRequired()
                        .HasConstraintName("social_network_data_candidate_fkey");

                    b.HasOne("CandidateSelectionService.Core.Entities.SocialNetworkType", "SocialNetworkType")
                        .WithMany("SocialNetworks")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("social_network_social_type_fkey");

                    b.Navigation("DataCandidate");

                    b.Navigation("SocialNetworkType");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.VerificationEvent", b =>
                {
                    b.HasOne("CandidateSelectionService.Core.Entities.Verification", "Verification")
                        .WithMany("VerificationEvents")
                        .HasForeignKey("VerificationId")
                        .IsRequired()
                        .HasConstraintName("verification_event_verification_id_fkey");

                    b.Navigation("Verification");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.VerificationEventResult", b =>
                {
                    b.HasOne("CandidateSelectionService.Core.Entities.VerificationEvent", "VerificationEvent")
                        .WithMany("VerificationEventResults")
                        .HasForeignKey("VerificationEventId")
                        .IsRequired()
                        .HasConstraintName("verification_event_result_verification_event_id_fkey");

                    b.Navigation("VerificationEvent");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.DataCandidate", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("Employee");

                    b.Navigation("SocialNetworks");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.SocialNetworkType", b =>
                {
                    b.Navigation("SocialNetworks");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.Verification", b =>
                {
                    b.Navigation("VerificationEvents");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.VerificationEvent", b =>
                {
                    b.Navigation("VerificationEventResults");
                });

            modelBuilder.Entity("CandidateSelectionService.Core.Entities.WorkSchedule", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
